title: Easy Tech Seniors
description: Friendly, patient tech help and seminars for seniors.
url: "https://price2high.github.io"
baseurl: "/SunnySideIT"
theme: minima

minima:
  skin: classic

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

collections:
  pages:
    output: true
    permalink: /:name/
