title: Easy Tech Seniors
description: Friendly, patient tech help and seminars for seniors.
baseurl: ""
url: ""
theme: minima
minima:
  skin: classic
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  pages:
    output: true
    permalink: /:name/
